name: Process ./scripts/*

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Darklua
        run: |
          curl -L "https://github.com/seaofvoices/darklua/releases/download/v0.16.0/darklua-linux-x86_64.zip" -o darklua.zip
          unzip darklua.zip
          chmod +x darklua

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm install @actions/github

      - name: Process ./scripts/* directory
        env:
          USER_GIST_PAT: ${{ secrets.USER_GIST_PAT }}
        id: process_scripts
        uses: actions/github-script@v7
        with:
          script: |
            const path = require("path");
            return require(path.resolve(".github/workflows/script_processor.js"))(context, core)

      - name: Upload output of processed scripts
        if: steps.process_scripts.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: scripts_output
          path: ./_output/
          retention-days: 7
